name: Deploy

on:
  push:
    tags: v*
    
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
    - name: Install Crystal
      uses: crystal-lang/install-crystal@v1
      
    - name: Run release build
      run: shards build --release
    - name: Pack release file
      run: |
        cp ./bin/tablet_scanner .
        tar -zcvf tablet_scanner-${{ matrix.os }}-${{ github.ref_name}}.tar.gz tablet_scanner

    - name: "Upload artifact"
      uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.os }}
        path: tablet_scanner-${{ matrix.os }}-${{ github.ref_name}}.tar.gz

  build-windows:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install Crystal
      uses: crystal-lang/install-crystal@v1
      
    - name: Run release build
      run: shards build --release

    - name: Pack release file
      run: |
        Copy bin/tablet_scanner.exe ./tablet_scanner.exe
        tar -a -c -f tablet_scanner-windows-${{ github.ref_name }}.zip tablet_scanner.exe

    - name: "Upload artifact"
      uses: actions/upload-artifact@v3
      with:
        name: windows-latest
        path: tablet_scanner-windows-${{ github.ref_name }}.zip

  release:
    needs: [build, build-windows]
    runs-on: ubuntu-latest

    steps:
    - name: "Download binaries"
      uses: actions/download-artifact@v2

    - name: "Move binaries"
      run: |
        mv ubuntu-latest/tablet_scanner-ubuntu-latest-${{ github.ref_name }}.tar.gz tablet_scanner-linux-${{ github.ref_name }}.tar.gz
        mv macos-latest/tablet_scanner-macos-latest-${{ github.ref_name }}.tar.gz .
        mv windows-latest/tablet_scanner-windows-${{ github.ref_name }}.zip .

    - name: "Automatic Release"
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: false
        title: "${{ github.ref_name }}"
        files: |
          tablet_scanner-*.tar.gz
          tablet_scanner-*.zip
